# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lights.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qlabelclickable import QLabelClickable
import tinytuya

class Ui_Lights(object):
    def setupUi(self, Lights):
        Lights.setObjectName("Lights")
        Lights.resize(793, 466)
        self.frame = QtWidgets.QFrame(Lights)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 480))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.background = QtWidgets.QLabel(self.frame)
        self.background.setGeometry(QtCore.QRect(0, 0, 800, 480))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.background.sizePolicy().hasHeightForWidth())
        self.background.setSizePolicy(sizePolicy)
        self.background.setText("")
        self.background.setTextFormat(QtCore.Qt.RichText)
        self.background.setPixmap(QtGui.QPixmap("icons/wallpaper.jpg"))
        self.background.setScaledContents(True)
        self.background.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.background.setWordWrap(False)
        self.background.setObjectName("background")
        self.lights = QLabelClickable(self.frame)
        self.lights.setGeometry(QtCore.QRect(370, 30, 81, 71))
        self.lights.setText("")
        self.lights.setTextFormat(QtCore.Qt.AutoText)
        self.lights.setPixmap(QtGui.QPixmap("icons/ic_lightbulb_black_48dp.png"))
        self.lights.setScaledContents(True)
        self.lights.setObjectName("lights")
        self.settings = QLabelClickable(self.frame)
        self.settings.setGeometry(QtCore.QRect(740, 420, 51, 51))
        self.settings.setText("")
        self.settings.setPixmap(QtGui.QPixmap("icons/baseline_settings_black_18dp.png"))
        self.settings.setScaledContents(True)
        self.settings.setObjectName("settings")
        self.ON = QLabelClickable(self.frame)
        self.ON.setGeometry(QtCore.QRect(360, 230, 101, 91))
        self.ON.setText("")
        self.ON.setPixmap(QtGui.QPixmap("icons/baseline_power_settings_new_black_18dp.png"))
        self.ON.setScaledContents(True)
        self.ON.setObjectName("ON")

        self.retranslateUi(Lights)
        QtCore.QMetaObject.connectSlotsByName(Lights)

        self.ON.clicked.connect(lambda local_widget=Lights: self.on_click_ON(local_widget))

    def retranslateUi(self, Lights):
        _translate = QtCore.QCoreApplication.translate
        Lights.setWindowTitle(_translate("Lights", "Form"))

    def on_click_ON(self, Lights):
        d = tinytuya.OutletDevice('', '192.168.0.3', '')
        d.set_version(3.3)
        data = d.status()
        if data['dps']['1'] == False:
            d.turn_on(switch=1)
        else:
            d.turn_off(switch=1)
